"""add budget period fields

Revision ID: cceb33de3e29
Revises: ab6d5be13132
Create Date: 2026-07-28 22:29:00.167127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cceb33de3e29'
down_revision: Union[str, Sequence[str], None] = 'ab6d5be13132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('year', sa.String(), nullable=True))
    op.add_column('budgets', sa.Column('month', sa.String(), nullable=True))
    op.add_column('budgets', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'created_at')
    op.drop_column('budgets', 'month')
    op.drop_column('budgets', 'year')
    # ### end Alembic commands ###
